### ISSUE TITLE
last commit c4a2adc99906b982803ec44a6891e1ad0977a960 breaks the game

### ISSUE THREAD

**Issue by sergicolladosopra** [alketii/Herbi#1]
It seems last commit c4a2adc99906b982803ec44a6891e1ad0977a960 breaks the game :(

**Comment by ObaniGemini** [comment]
It works fine for me, have you a recent version of Godot ?

**Comment by alketii** [comment]
It was an error in between.tscn , which worked on project list but not in editor, fixed with 59c7a1907d7157aff9e9a4a7ea3201013ba34718

**Comment by alketii** [comment]
It was an error in between.tscn , which worked on project list but not in editor, fixed with 59c7a1907d7157aff9e9a4a7ea3201013ba34718

**Comment by alketii** [comment]
It was an error in between.tscn , which worked on project list but not in editor, fixed with 59c7a1907d7157aff9e9a4a7ea3201013ba34718
