### ISSUE TITLE
Can't edit levels with tiled

### ISSUE THREAD

**Issue by DeRobyJ** [alketii/Herbi#11]
When opening any level with tiled from linux, I get this error:
Invalid (nonconsecutive) tile ID: 5
Line 28, column 15

Also, to create new levels, I should copy the blank level and name it level_<newNumber>, non level_0, isn't it?

**Comment by alketii** [comment]
Which Tiled Version do you have, I think you need the latest version.

**Comment by DeRobyJ** [comment]
Added this repo
https://launchpad.net/~mapeditor.org/+archive/ubuntu/tiled/+packages

installed tiled-daily

now it works!

edit: 
for future reference: this way should work in any ubuntu 14 distro. In my case, it was kxstudio 14..04.2

**Comment by ObaniGemini** [comment]
Indeed it should be level_blank renamed as level_x. But you can use every level and modify it since you rename it, no problem on that :)
