### ISSUE TITLE
The problem of replacing tiled by tilemap

### ISSUE THREAD

**Issue by ObaniGemini** [alketii/Herbi#17]
We've been talking on IRC about replacing Tiled and its converters by tilemap and some converters.
The advantages would be that all the tools would be local and then it would be easier to tweak stuff.

As a converter tool, we could have tiles being interpreted by a script to be deleted and replaced by the node they refer to (example : spikes, enemies, player,...)

The idea would be to have less Node2Ds per-level, but also to ease the editing of levels without having to use a ton of more tools (take a look at [levels/](https://github.com/KOBUGE-Games/Herbi/tree/master/levels) to see the mess)

BUT. Since my last changes, nearly all the nodes now are banks of sprites so can't be used as tiles as they have several possible sprites. This puts a lot of nodes to be added to the converter script and makes the presence of the tiles *sorted from the tilemap* really minimal.

**So what we have is :**
:+1: => Less third-party tools to work with and to keep on the repo
:+1: => Faster and easier to edit levels
:question: => Is it worth making it on performance-side ?
:-1: => Some time of work and want to be taken to make it *and to assure it works*. Not so hard but needs someone to do it.

My most important question would then be : should we remove the sprite banks of : stones, dirt_mid, 
grassstone_mid and others ? ( [tiles](https://github.com/KOBUGE-Games/Herbi/tree/master/graphics/tiles) ).
If we choose to remove them, I'd be totally for the new system.
Else,...?

**Comment by alketii** [comment]
Yeah, this should be our first task for the next version.

**Comment by ObaniGemini** [comment]
Too bored for doing such a thing
