### ISSUE TITLE
Some sound problems

### ISSUE THREAD

**Issue by ObaniGemini** [alketii/Herbi#6]
##### Positionnal audio not working properly

Sounds are played on positionnal as if they were on the vertical left axis of the level. This makes sounds being played lower and lower and with less and less high frequencies when you go to the right vertical axis of the level (this is more obvious in big levels).

EDIT : this is not on a vertical axis but the sound source is in the top left corner
##### Game sounds are only played on one speaker

Everything in the title. This is probably because sounds are encoded in mono and not in stereo. Should e reencode them in stereo then ?

**Comment by bojidar-bg** [comment]
The problem with positional audio is that there is only one SamplePlayer2D, while there should either be many sample players (one for each e**n**emy), or just one SamplePlayer (not 2D)

**Comment by ObaniGemini** [comment]
@bojidar-bg : I think it should be one SamplePlayer.

We should remove at least 5db to the jumping sound recently added also, and maybe a pitch randomization exceptionally

**Comment by ObaniGemini** [comment]
https://github.com/KOBUGE-Games/Herbi/commit/ef0f45a2944c9ed46cd7c43cf0fceb3b7dbd58cc
Thanks @bojidar-bg for the help and @alketii 's code to learn how to do that :)
