### ISSUE TITLE
Between scene features

### ISSUE THREAD

**Issue by ObaniGemini** [alketii/Herbi#8]
#### Bug Fix
- [ ] Make the between screen a little bit longer for the jingle is fully played. Should we make the "level" larger for that ?
#### Feature Idea

I thought that it could be cool if we had several between scenes played randomly, or some between scenes accorded to the universe ( e.g : cave world, cave between scene, aerial world, aerial between scene,...)

**Comment by ObaniGemini** [comment]
Up,  we need the bug fixed for the next release. Maybe keep the screen 1 second on before Herbi enters it ?

**Comment by DeRobyJ** [comment]
I agree
When you get the last diamond, it the game should freeze a second and then pass to the between scene. And this would allow music to be played longer!

**Comment by ObaniGemini** [comment]
Gonna do t with some other things I guess

**Comment by ObaniGemini** [comment]
Actually I removed this scene cause it was annoying. I made something else instead, tell if you don't like (might make a sound for it someday)
