### ISSUE TITLE
Unability to kill an enemy

### ISSUE THREAD

**Issue by ObaniGemini** [alketii/Herbi#9]
In level_6 the lower enemy (a monkey) cannot be killed, I think it's because of some spikes but I thought I had removed them
Error : 
SCRIPT ERROR: _on_Area2D_body_enter: Invalid get index 'velocity' (on base: 'StaticBody2D (spikes.gd)').
   At: res://scripts/enemy_2.gd:80.
SCRIPT ERROR: _on_Area2D_body_enter: Invalid get index 'velocity' (on base: 'StaticBody2D (spikes.gd)').
   At: res://scripts/enemy_2.gd:80.

![blablabla](https://lut.im/Nm8h4G4585/N74LnTnMttfCHXM8.png)

**Comment by bojidar-bg** [comment]
@ObaniGemini ~ I think I fixed it in 1c09d538d84396c72b45b0d27d31fb8f2ae5ba7c, please check again.

**Comment by ObaniGemini** [comment]
@bojidar-bg : it was fixed indeed. Thanks for your work :)
